### ISSUE TITLE
Use of CDATA for software names

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/android-mdm-library#5]
**Describe the bug**
The XML generate doesn't handle the names with spacial chars like "&" which gives a XML malformed.

**To Reproduce**
1. Install an app like Kingdoms & Lords (com.gameloft.android.GloftKLMF)
2. Generate an inventory
3. Check the software name

**Expected behavior**
The software names must use the CDATA node to escape the special chars

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1426313/39604618-f2ce9caa-4efa-11e8-9e5b-8317b6ac4f85.png)

**Comment by ajsb85** [comment]
PING @g-bougard

**Comment by rafaelje** [comment]
This is not the inventory library we need move this issue:
https://github.com/flyve-mdm/android-inventory-library

**Comment by DIOHz0r** [comment]
Moved the issue to the correct project...
https://github.com/flyve-mdm/android-inventory-library/issues/113
